#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// For directory creation
#ifdef _WIN32
    #include <direct.h> // For _mkdir
    #define MKDIR(path) _mkdir(path)
    #define PATH_SEPARATOR '\\'
#else
    #include <sys/stat.h> // For mkdir (POSIX)
    #include <sys/types.h> // For mkdir (POSIX)
    #define MKDIR(path) mkdir(path, 0755)
    #define PATH_SEPARATOR '/'
#endif

#define MAX_PATH_LEN 1024
#define PROJECT_NAME "cluster_node"

// Function prototypes
void create_directory_recursive(const char *path);
void create_file_with_content(const char *filepath, const char *content);

// --- Django Core File Contents ---
const char* manage_py_content =
"#!/usr/bin/env python\n"
"\"\"\"Django's command-line utility for administrative tasks.\"\"\"\n"
"import os\n"
"import sys\n"
"\n"
"def main():\n"
"    \"\"\"Run administrative tasks.\"\"\"\n"
"    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cluster_node.settings')\n"
"    try:\n"
"        from django.core.management import execute_from_command_line\n"
"    except ImportError as exc:\n"
"        raise ImportError(\n"
"            \"Couldn't import Django. Are you sure it's installed and \"\n"
"            \"available on your PYTHONPATH environment variable? Did you \"\n"
"            \"forget to activate a virtual environment?\"\n"
"        ) from exc\n"
"    execute_from_command_line(sys.argv)\n"
"\n"
"if __name__ == '__main__':\n"
"    main()\n";

const char* requirements_txt_content =
"Django>=3.2,<4.3\n"
"djangorestframework>=3.12,<3.15\n"
"requests>=2.25,<3.0\n";

const char* init_py_content = "";

const char* settings_py_content =
"\"\"\"\n"
"Django settings for cluster_node project.\n"
"Generated by cluster_django_generator.\n"
"\"\"\"\n"
"\n"
"from pathlib import Path\n"
"import os\n"
"\n"
"BASE_DIR = Path(__file__).resolve().parent.parent\n"
"\n"
"SECRET_KEY = \"django-insecure-replace-this-in-production\"\n"
"DEBUG = True\n"
"ALLOWED_HOSTS = []\n"
"\n"
"INSTALLED_APPS = [\n"
"    'django.contrib.admin',\n"
"    'django.contrib.auth',\n"
"    'django.contrib.contenttypes',\n"
"    'django.contrib.sessions',\n"
"    'django.contrib.messages',\n"
"    'django.contrib.staticfiles',\n"
"    'nodes.apps.NodesConfig',\n"
"    'rest_framework',\n"
"]\n"
"\n"
"MIDDLEWARE = [\n"
"    'django.middleware.security.SecurityMiddleware',\n"
"    'django.contrib.sessions.middleware.SessionMiddleware',\n"
"    'django.middleware.common.CommonMiddleware',\n"
"    'django.middleware.csrf.CsrfViewMiddleware',\n"
"    'django.contrib.auth.middleware.AuthenticationMiddleware',\n"
"    'django.contrib.messages.middleware.MessageMiddleware',\n"
"    'django.middleware.clickjacking.XFrameOptionsMiddleware',\n"
"]\n"
"\n"
"ROOT_URLCONF = 'cluster_node.urls'\n"
"\n"
"TEMPLATES = [\n"
"    {\n"
"        'BACKEND': 'django.template.backends.django.DjangoTemplates',\n"
"        'DIRS': [BASE_DIR / 'templates'],\n"
"        'APP_DIRS': True,\n"
"        'OPTIONS': {\n"
"            'context_processors': [\n"
"                'django.template.context_processors.debug',\n"
"                'django.template.context_processors.request',\n"
"                'django.contrib.auth.context_processors.auth',\n"
"                'django.contrib.messages.context_processors.messages',\n"
"            ],\n"
"        },\n"
"    },\n"
"]\n"
"\n"
"WSGI_APPLICATION = 'cluster_node.wsgi.application'\n"
"\n"
"DATABASES = {\n"
"    'default': {\n"
"        'ENGINE': 'django.db.backends.sqlite3',\n"
"        'NAME': BASE_DIR / 'db.sqlite3',\n"
"    }\n"
"}\n"
"\n"
"AUTH_PASSWORD_VALIDATORS = [\n"
"    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},\n"
"    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},\n"
"    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},\n"
"    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},\n"
"]\n"
"\n"
"LANGUAGE_CODE = 'en-us'\n"
"TIME_ZONE = 'UTC'\n"
"USE_I18N = True\n"
"USE_L10N = True\n"
"USE_TZ = True\n"
"\n"
"STATIC_URL = '/static/'\n"
"STATICFILES_DIRS = [BASE_DIR / 'static']\n"
"\n"
"DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'\n"
"\n"
"LOGIN_URL = '/login/'\n"
"LOGIN_REDIRECT_URL = '/dashboard/'\n";

const char* project_urls_py_content =
"from django.contrib import admin\n"
"from django.urls import path, include\n"
"from django.views.generic import TemplateView\n"
"from django.contrib.auth import views as auth_views\n"
"\n"
"urlpatterns = [\n"
"    path('admin/', admin.site.urls),\n"
"    path('', TemplateView.as_view(template_name='index.html'), name='index'),\n"
"    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),\n"
"    path('logout/', auth_views.LogoutView.as_view(next_page='index'), name='logout'),\n"
"    path('', include('nodes.urls')),\n"
"]\n";

const char* wsgi_py_content =
"import os\n"
"from django.core.wsgi import get_wsgi_application\n"
"os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cluster_node.settings')\n"
"application = get_wsgi_application()\n";

const char* asgi_py_content =
"import os\n"
"from django.core.asgi import get_asgi_application\n"
"os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cluster_node.settings')\n"
"application = get_asgi_application()\n";

// --- 'nodes' App File Contents ---
const char* nodes_init_py_content = "";
const char* nodes_apps_py_content =
"from django.apps import AppConfig\n"
"\n"
"class NodesConfig(AppConfig):\n"
"    default_auto_field = 'django.db.models.BigAutoField'\n"
"    name = 'nodes'\n";

const char* nodes_models_py_content =
"from django.db import models\n"
"import uuid\n"
"\n"
"class Node(models.Model):\n"
"    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)\n"
"    ip = models.GenericIPAddressField()\n"
"    location = models.CharField(max_length=100)  # E.g., 'PB', 'SP', 'MG'\n"
"    status = models.CharField(max_length=10, choices=[('online', 'Online'), ('offline', 'Offline')], default='offline')\n"
"    last_update = models.DateTimeField(auto_now=True)\n"
"\n"
"    def __str__(self):\n"
"        return f'{self.location} ({self.ip}) - {self.status}'\n";

const char* nodes_admin_py_content =
"from django.contrib import admin\n"
"from .models import Node\n"
"\n"
"@admin.register(Node)\n"
"class NodeAdmin(admin.ModelAdmin):\n"
"    list_display = ('id', 'ip', 'location', 'status', 'last_update')\n"
"    list_filter = ('status', 'location')\n"
"    search_fields = ('ip', 'location')\n";

const char* nodes_serializers_py_content =
"from rest_framework import serializers\n"
"from .models import Node\n"
"\n"
"class NodeSerializer(serializers.ModelSerializer):\n"
"    class Meta:\n"
"        model = Node\n"
"        fields = ['id', 'ip', 'location', 'status', 'last_update']\n"
"        read_only_fields = ['id', 'last_update']\n"
"\n"
"class NodeRegistrationSerializer(serializers.ModelSerializer):\n"
"    class Meta:\n"
"        model = Node\n"
"        fields = ['ip', 'location']\n"
"\n"
"class NodeStatusUpdateSerializer(serializers.Serializer):\n"
"    node_id = serializers.UUIDField(required=False)\n"
"    status = serializers.ChoiceField(choices=[('online', 'Online'), ('offline', 'Offline')])\n";

const char* nodes_views_py_content =
"from django.shortcuts import render, get_object_or_404\n"
"from django.contrib.auth.decorators import login_required\n"
"from .models import Node\n"
"from .serializers import NodeSerializer, NodeRegistrationSerializer, NodeStatusUpdateSerializer\n"
"\n"
"from rest_framework import generics, status, views\n"
"from rest_framework.response import Response\n"
"from rest_framework.permissions import AllowAny, IsAuthenticated\n"
"\n"
"@login_required\n"
"def dashboard_view(request):\n"
"    nodes = Node.objects.all()\n"
"    return render(request, 'dashboard.html', {'nodes': nodes, 'user': request.user})\n"
"\n"
"class NodeListAPIView(generics.ListAPIView):\n"
"    queryset = Node.objects.all()\n"
"    serializer_class = NodeSerializer\n"
"    permission_classes = [IsAuthenticated]\n"
"\n"
"class NodeRegisterAPIView(generics.CreateAPIView):\n"
"    queryset = Node.objects.all()\n"
"    serializer_class = NodeRegistrationSerializer\n"
"    permission_classes = [AllowAny]\n"
"\n"
"    def perform_create(self, serializer):\n"
"        serializer.save(status='online')\n"
"\n"
"class NodeTaskAPIView(views.APIView):\n"
"    permission_classes = [AllowAny]\n"
"\n"
"    def get(self, request, *args, **kwargs):\n"
"        task_data = {\n"
"            'task_id': 'task_123',\n"
"            'type': 'simple_math',\n"
"            'instruction': 'Add the numbers.',\n"
"            'data': {'a': 10, 'b': 25}\n"
"        }\n"
"        return Response(task_data, status=status.HTTP_200_OK)\n"
"\n"
"class NodeStatusUpdateAPIView(views.APIView):\n"
"    permission_classes = [AllowAny]\n"
"\n"
"    def post(self, request, *args, **kwargs):\n"
"        node_ip = request.data.get('ip')\n"
"        new_status = request.data.get('status')\n"
"\n"
"        if not node_ip or not new_status:\n"
"            return Response({'error': 'IP and status are required.'}, status=status.HTTP_400_BAD_REQUEST)\n"
"\n"
"        try:\n"
"            node = Node.objects.get(ip=node_ip)\n"
"            if new_status not in ['online', 'offline']:\n"
"                 return Response({'error': 'Invalid status value.'}, status=status.HTTP_400_BAD_REQUEST)\n"
"            node.status = new_status\n"
"            node.save(update_fields=['status', 'last_update'])\n"
"            return Response(NodeSerializer(node).data, status=status.HTTP_200_OK)\n"
"        except Node.DoesNotExist:\n"
"            return Response({'error': 'Node not found.'}, status=status.HTTP_404_NOT_FOUND)\n"
"        except Exception as e:\n"
"            return Response({'error': str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)\n";

const char* nodes_urls_py_content =
"from django.urls import path\n"
"from . import views\n"
"\n"
"urlpatterns = [\n"
"    path('dashboard/', views.dashboard_view, name='dashboard'),\n"
"\n"
"    path('api/nodes/', views.NodeListAPIView.as_view(), name='api-node-list'),\n"
"    path('api/register/', views.NodeRegisterAPIView.as_view(), name='api-node-register'),\n"
"    path('api/task/', views.NodeTaskAPIView.as_view(), name='api-node-task'),\n"
"    path('api/status/', views.NodeStatusUpdateAPIView.as_view(), name='api-node-status'),\n"
"]\n";

// --- Template and Static File Contents ---
const char* templates_base_html_content =
"{% load static %}\n"
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <title>{% block title %}Cluster Node{% endblock %}</title>\n"
"    <link rel=\"stylesheet\" href=\"{% static 'css/style.css' %}\">\n"
"</head>\n"
"<body>\n"
"    <nav>\n"
"        <a href=\"{% url 'index' %}\">Home</a>\n"
"        {% if user.is_authenticated %}\n"
"            <a href=\"{% url 'dashboard' %}\">Dashboard</a>\n"
"            <a href=\"{% url 'logout' %}\">Logout</a>\n"
"        {% else %}\n"
"            <a href=\"{% url 'login' %}\">Login</a>\n"
"        {% endif %}\n"
"    </nav>\n"
"    <div class=\"container\">\n"
"        {% block content %}{% endblock %}\n"
"    </div>\n"
"</body>\n"
"</html>\n";

const char* templates_index_html_content =
"{% extends 'base.html' %}\n"
"{% block title %}Home - Cluster Node{% endblock %}\n"
"{% block content %}\n"
"<h1>Welcome to Cluster Node</h1>\n"
"<p>This is the public home page.</p>\n"
"<p>Login to access the dashboard and manage nodes.</p>\n"
"{% endblock %}\n";

const char* templates_login_html_content =
"{% extends 'base.html' %}\n"
"{% block title %}Login - Cluster Node{% endblock %}\n"
"{% block content %}\n"
"<h2>Login</h2>\n"
"<form method=\"post\">\n"
"    {% csrf_token %}\n"
"    {{ form.as_p }}\n"
"    <button type=\"submit\">Login</button>\n"
"</form>\n"
"{% endblock %}\n";

const char* templates_dashboard_html_content =
"{% extends \"base.html\" %}\n"
"{% load static %}\n"
"{% block title %}Dashboard - Cluster Node{% endblock %}\n"
"\n"
"{% block content %}\n"
"<h1>Dashboard</h1>\n"
"<p>Welcome, {{ user.username }}!</p>\n"
"\n"
"<h2>Registered Nodes</h2>\n"
"<div id=\"node-list-table\">\n"
"    {% if nodes %}\n"
"        <table>\n"
"            <thead>\n"
"                <tr>\n"
"                    <th>ID</th>\n"
"                    <th>IP Address</th>\n"
"                    <th>Location</th>\n"
"                    <th>Status</th>\n"
"                    <th>Last Update</th>\n"
"                </tr>\n"
"            </thead>\n"
"            <tbody>\n"
"                {% for node in nodes %}\n"
"                <tr id=\"node-{{ node.id }}\">\n"
"                    <td>{{ node.id }}</td>\n"
"                    <td>{{ node.ip }}</td>\n"
"                    <td class=\"node-location\">{{ node.location }}</td>\n"
"                    <td class=\"node-status\">{{ node.status }}</td>\n"
"                    <td>{{ node.last_update|date:\"Y-m-d H:i:s\" }}</td>\n"
"                </tr>\n"
"                {% endfor %}\n"
"            </tbody>\n"
"        </table>\n"
"    {% else %}\n"
"        <p>No nodes registered yet.</p>\n"
"    {% endif %}\n"
"</div>\n"
"\n"
"<h2>Node Status Map</h2>\n"
"<div id=\"map-container\" style=\"max-width: 600px; margin: auto;\">\n"
"    {% include \"mapa_brasil.svg\" %}\n"
"</div>\n"
"\n"
"<script>\n"
"document.addEventListener(\"DOMContentLoaded\", function() {\n"
"    const mapContainer = document.getElementById(\"map-container\");\n"
"    const nodeListTable = document.getElementById(\"node-list-table\");\n"
"\n"
"    function updateNodeDisplay(nodesData) {\n"
"        const svgMap = mapContainer.querySelector(\"#brazil-map\");\n"
"        if (svgMap) {\n"
"            svgMap.querySelectorAll(\".state\").forEach(statePath => {\n"
"                statePath.classList.remove(\"online\", \"offline\");\n"
"                statePath.classList.add(\"unknown\");\n"
"            });\n"
"\n"
"            nodesData.forEach(node => {\n"
"                const stateElement = svgMap.querySelector(\"#\" + node.location);\n"
"                if (stateElement) {\n"
"                    stateElement.classList.remove(\"unknown\", \"offline\", \"online\");\n"
"                    if (node.status === \"online\") {\n"
"                        stateElement.classList.add(\"online\");\n"
"                    } else {\n"
"                        stateElement.classList.add(\"offline\");\n"
"                    }\n"
"                }\n"
"            });\n"
"        }\n"
"\n"
"        let tableHTML = \"<table><thead><tr><th>ID</th><th>IP Address</th><th>Location</th><th>Status</th><th>Last Update</th></tr></thead><tbody>\";\n"
"        if (nodesData && nodesData.length > 0) {\n"
"            nodesData.forEach(node => {\n"
"                let formattedDate = \"N/A\";\n"
"                if (node.last_update) {\n"
"                    try {\n"
"                        const date = new Date(node.last_update);\n"
"                        formattedDate = date.toLocaleString();\n"
"                    } catch (e) {\n"
"                        formattedDate = node.last_update;\n"
"                    }\n"
"                }\n"
"                tableHTML += `<tr>\n"
"                                <td>${node.id}</td>\n"
"                                <td>${node.ip}</td>\n"
"                                <td>${node.location}</td>\n"
"                                <td>${node.status}</td>\n"
"                                <td>${formattedDate}</td>\n"
"                              </tr>`;\n"
"            });\n"
"            tableHTML += \"</tbody></table>\";\n"
"        } else {\n"
"            tableHTML = \"<p>No nodes registered yet.</p>\";\n"
"        }\n"
"        nodeListTable.innerHTML = tableHTML;\n"
"    }\n"
"\n"
"    function fetchNodeData() {\n"
"        fetch(\"/api/nodes/\", {\n"
"            method: \"GET\",\n"
"            headers: { \"Accept\": \"application/json\" }\n"
"        })\n"
"        .then(response => {\n"
"            if (response.status === 403) {\n"
"                console.warn(\"Failed to fetch node data: Permission denied.\");\n"
"                return null;\n"
"            }\n"
"            if (!response.ok) {\n"
"                throw new Error(\"Network response was not ok for /api/nodes/\");\n"
"            }\n"
"            return response.json();\n"
"        })\n"
"        .then(data => {\n"
"            if (data) {\n"
"                updateNodeDisplay(data);\n"
"            }\n"
"        })\n"
"        .catch(error => {\n"
"            console.error(\"Error fetching node data:\", error);\n"
"        });\n"
"    }\n"
"    \n"
"    fetchNodeData();\n"
"    setInterval(fetchNodeData, 10000);\n"
"});\n"
"</script>\n"
"{% endblock %}\n";

const char* templates_mapa_brasil_svg_content =
"<svg viewBox=\"0 0 300 300\" xmlns=\"http://www.w3.org/2000/svg\" id=\"brazil-map\">\n"
"    <style>\n"
"        .state { stroke: #333; stroke-width: 1px; transition: fill 0.3s ease; }\n"
"        .state.online { fill: #4CAF50; /* Green */ }\n"
"        .state.offline { fill: #F44336; /* Red */ }\n"
"        .state.unknown { fill: #9E9E9E; /* Grey for states with no node or unknown status */ }\n"
"    </style>\n"
"    <rect width=\"100%\" height=\"100%\" fill=\"#f0f0f0\" />\n"
"    \n"
"    <path id=\"SP\" class=\"state unknown\" d=\"M100,150 l20,0 l0,20 l-20,0 z\" data-name=\"São Paulo\"></path>\n"
"    <text x=\"110\" y=\"165\" font-size=\"8\" text-anchor=\"middle\">SP</text>\n"
"    <path id=\"RJ\" class=\"state unknown\" d=\"M130,170 l20,0 l0,15 l-20,0 z\" data-name=\"Rio de Janeiro\"></path>\n"
"    <text x=\"140\" y=\"180\" font-size=\"8\" text-anchor=\"middle\">RJ</text>\n"
"    <path id=\"MG\" class=\"state unknown\" d=\"M110,120 l30,0 l10,20 l-30,10 z\" data-name=\"Minas Gerais\"></path>\n"
"    <text x=\"125\" y=\"135\" font-size=\"8\" text-anchor=\"middle\">MG</text>\n"
"    <path id=\"BA\" class=\"state unknown\" d=\"M150,100 l25,0 l5,25 l-20,5 z\" data-name=\"Bahia\"></path>\n"
"    <text x=\"165\" y=\"115\" font-size=\"8\" text-anchor=\"middle\">BA</text>\n"
"    <path id=\"PR\" class=\"state unknown\" d=\"M90,180 l20,0 l0,20 l-20,0 z\" data-name=\"Paraná\"></path>\n"
"    <text x=\"100\" y=\"195\" font-size=\"8\" text-anchor=\"middle\">PR</text>\n"
"    <path id=\"RS\" class=\"state unknown\" d=\"M80,210 l20,0 l0,20 l-20,0 z\" data-name=\"Rio Grande do Sul\"></path>\n"
"    <text x=\"90\" y=\"225\" font-size=\"8\" text-anchor=\"middle\">RS</text>\n"
"    <path id=\"AM\" class=\"state unknown\" d=\"M50,50 l40,10 l10,40 l-50,0 z\" data-name=\"Amazonas\"></path>\n"
"    <text x=\"70\" y=\"80\" font-size=\"8\" text-anchor=\"middle\">AM</text>\n"
"    \n"
"    <text x=\"150\" y=\"20\" font-size=\"12\" text-anchor=\"middle\">Simplified Map of Brazil - Node Status</text>\n"
"</svg>\n";

const char* static_css_style_css_content =
"body {\n"
"    font-family: Arial, sans-serif;\n"
"    margin: 0;\n"
"    padding: 0;\n"
"    background-color: #f4f4f4;\n"
"    color: #333;\n"
"}\n"
".container {\n"
"    width: 80%;\n"
"    margin: auto;\n"
"    overflow: hidden;\n"
"    padding: 20px;\n"
"    background-color: #fff;\n"
"    box-shadow: 0 0 10px rgba(0,0,0,0.1);\n"
"}\n"
"nav {\n"
"    background: #333;\n"
"    color: #fff;\n"
"    padding: 10px 0;\n"
"    text-align: center;\n"
"}\n"
"nav a {\n"
"    color: #fff;\n"
"    margin: 0 15px;\n"
"    text-decoration: none;\n"
"}\n"
"nav a:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"h1, h2 {\n"
"    color: #333;\n"
"}\n"
"table {\n"
"    width: 100%;\n"
"    border-collapse: collapse;\n"
"    margin-top: 20px;\n"
"}\n"
"table, th, td {\n"
"    border: 1px solid #ddd;\n"
"}\n"
"th, td {\n"
"    padding: 8px;\n"
"    text-align: left;\n"
"}\n"
"th {\n"
"    background-color: #f2f2f2;\n"
"}\n"
"button {\n"
"    padding: 10px 15px;\n"
"    background-color: #333;\n"
"    color: #fff;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"}\n"
"button:hover {\n"
"    background-color: #555;\n"
"}\n"
"form p { margin-bottom: 10px; }\n"
"form p label { display: block; margin-bottom: 5px; }\n"
"form p input[type=\"text\"], form p input[type=\"password\"] {\n"
"    width: calc(100% - 22px);\n"
"    padding: 10px;\n"
"    border: 1px solid #ddd;\n"
"}\n"
"\n"
"#map-container {\n"
"    margin-top: 20px;\n"
"    border: 1px solid #ccc;\n"
"}\n";

// --- Main Function ---
int main() {
    printf("Starting Django project generation for '%s'\\n", PROJECT_NAME);

    create_directory_recursive(PROJECT_NAME);

    char path_buffer[MAX_PATH_LEN];

    printf("\\n--- Creating standard project directories ---\\n");
    snprintf(path_buffer, MAX_PATH_LEN, "%s%ctemplates", PROJECT_NAME, PATH_SEPARATOR);
    create_directory_recursive(path_buffer);
    snprintf(path_buffer, MAX_PATH_LEN, "%s%cstatic%ccss", PROJECT_NAME, PATH_SEPARATOR, PATH_SEPARATOR);
    create_directory_recursive(path_buffer);

    printf("\\n--- Creating app 'nodes' directories ---\\n");
    snprintf(path_buffer, MAX_PATH_LEN, "%s%cnodes%cmigrations", PROJECT_NAME, PATH_SEPARATOR, PATH_SEPARATOR);
    create_directory_recursive(path_buffer);

    printf("\\n--- Creating inner project config directory ---\\n");
    snprintf(path_buffer, MAX_PATH_LEN, "%s%c%s", PROJECT_NAME, PATH_SEPARATOR, PROJECT_NAME);
    create_directory_recursive(path_buffer);

    printf("\\nDirectory structure created successfully.\\n");

    char filepath_buffer[MAX_PATH_LEN];

    printf("\\n--- Generating core project files ---\\n");
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%cmanage.py", PROJECT_NAME, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, manage_py_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%crequirements.txt", PROJECT_NAME, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, requirements_txt_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%c%s%c__init__.py", PROJECT_NAME, PATH_SEPARATOR, PROJECT_NAME, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, init_py_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%c%s%csettings.py", PROJECT_NAME, PATH_SEPARATOR, PROJECT_NAME, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, settings_py_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%c%s%curls.py", PROJECT_NAME, PATH_SEPARATOR, PROJECT_NAME, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, project_urls_py_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%c%s%cwsgi.py", PROJECT_NAME, PATH_SEPARATOR, PROJECT_NAME, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, wsgi_py_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%c%s%casgi.py", PROJECT_NAME, PATH_SEPARATOR, PROJECT_NAME, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, asgi_py_content);
    printf("\\nCore project files generated.\\n");

    printf("\\n--- Generating 'nodes' app files ---\\n");
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%cnodes%c__init__.py", PROJECT_NAME, PATH_SEPARATOR, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, nodes_init_py_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%cnodes%capps.py", PROJECT_NAME, PATH_SEPARATOR, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, nodes_apps_py_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%cnodes%cmodels.py", PROJECT_NAME, PATH_SEPARATOR, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, nodes_models_py_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%cnodes%cadmin.py", PROJECT_NAME, PATH_SEPARATOR, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, nodes_admin_py_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%cnodes%cserializers.py", PROJECT_NAME, PATH_SEPARATOR, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, nodes_serializers_py_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%cnodes%cviews.py", PROJECT_NAME, PATH_SEPARATOR, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, nodes_views_py_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%cnodes%curls.py", PROJECT_NAME, PATH_SEPARATOR, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, nodes_urls_py_content);
    printf("\\n'nodes' app files generated.\\n");

    printf("\\n--- Generating template and static files ---\\n");
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%ctemplates%cbase.html", PROJECT_NAME, PATH_SEPARATOR, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, templates_base_html_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%ctemplates%cindex.html", PROJECT_NAME, PATH_SEPARATOR, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, templates_index_html_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%ctemplates%clogin.html", PROJECT_NAME, PATH_SEPARATOR, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, templates_login_html_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%ctemplates%cdashboard.html", PROJECT_NAME, PATH_SEPARATOR, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, templates_dashboard_html_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%ctemplates%cmapa_brasil.svg", PROJECT_NAME, PATH_SEPARATOR, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, templates_mapa_brasil_svg_content);
    snprintf(filepath_buffer, MAX_PATH_LEN, "%s%cstatic%ccss%cstyle.css", PROJECT_NAME, PATH_SEPARATOR, PATH_SEPARATOR, PATH_SEPARATOR);
    create_file_with_content(filepath_buffer, static_css_style_css_content);
    printf("\\nTemplate and static files generated.\\n");

    printf("\\n--- Django Project Generation Complete ---\\n");
    return 0;
}

// --- Helper Function Implementations ---
void create_directory_simple(const char *path) {
    printf("Attempting to create directory: %s\\n", path);
    if (MKDIR(path) == 0) {
        printf("Successfully created directory: %s\\n", path);
    } else {
        printf("Directory '%s' may already exist or an error occurred.\\n", path);
    }
}

void create_directory_recursive(const char *path) {
    char tmp[MAX_PATH_LEN];
    char *p = NULL;
    size_t len;

    snprintf(tmp, sizeof(tmp),"%s",path);
    len = strlen(tmp);

    if(len == 0) return;
    if(tmp[len - 1] == PATH_SEPARATOR) {
        tmp[len - 1] = 0;
    }

    for(p = tmp + 1; *p; p++) {
        if(*p == PATH_SEPARATOR) {
            *p = 0;
            create_directory_simple(tmp);
            *p = PATH_SEPARATOR;
        }
    }
    create_directory_simple(tmp);
}

void create_file_with_content(const char *filepath, const char *content) {
    FILE *file = fopen(filepath, "w");
    if (file == NULL) {
        perror("Failed to open file for writing");
        fprintf(stderr, "Error creating file: %s\\n", filepath);
        return;
    }

    if (fprintf(file, "%s", content) < 0) {
        perror("Failed to write content to file");
        fprintf(stderr, "Error writing to file: %s\\n", filepath);
    } else {
        printf("Successfully created file: %s\\n", filepath);
    }

    fclose(file);
}
